In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [ ]:
#Numpy
#Pandas
#Matplotlib
#Seaborn

In [ ]:
#Numpy Operaciones con Arrays

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import time
import plotly.express as px

In [ ]:
# Desde listas de Python
lista_simple = [1, 2, 3, 4, 5]
array_1d = np.array(lista_simple)
print("Array 1D desde lista:", array_1d)

Array 1D desde lista: [1 2 3 4 5]


In [ ]:
# Array bidimensional
lista_anidada = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array_2d = np.array(lista_anidada)
print("\nArray 2D desde lista anidada:")
print(array_2d)


Array 2D desde lista anidada:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Funciones constructoras
print("\nArrays desde funciones constructoras:")
print("Ceros:", np.zeros(5))
print("Unos:", np.ones((2, 3)))
print("Valores constantes:", np.full((2, 2), 7))
print("Matriz identidad:", np.eye(3))
print("Valores aleatorios [0,1):", np.random.random((2, 2)))
print("Valores aleatorios normales:", np.random.normal(0, 1, (2, 2)))
print("Rango secuencial:", np.arange(0, 10, 2))
print("Rango espaciado uniformemente:", np.linspace(0, 1, 5))


Arrays desde funciones constructoras:
Ceros: [0. 0. 0. 0. 0.]
Unos: [[1. 1. 1.]
 [1. 1. 1.]]
Valores constantes: [[7 7]
 [7 7]]
Matriz identidad: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Valores aleatorios [0,1): [[0.70729678 0.77409516]
 [0.91560815 0.11803368]]
Valores aleatorios normales: [[-1.7919833   0.7999361 ]
 [-0.52283689 -0.26568055]]
Rango secuencial: [0 2 4 6 8]
Rango espaciado uniformemente: [0.   0.25 0.5  0.75 1.  ]


In [ ]:
#Atributos y propiedades de Arrays
# Crear un array de muestra
muestra = np.random.randint(0, 100, (3, 4, 5))

# Explorar atributos
print("Forma (dimensiones):", muestra.shape)
print("Número de dimensiones:", muestra.ndim)
print("Tipo de datos:", muestra.dtype)
print("Número total de elementos:", muestra.size)
print("Tamaño en bytes:", muestra.nbytes)

Forma (dimensiones): (3, 4, 5)
Número de dimensiones: 3
Tipo de datos: int64
Número total de elementos: 60
Tamaño en bytes: 480


In [ ]:
print(muestra)

[[[21 40 86 74 94]
  [25 72 60 86  1]
  [ 4 71 78 88 77]
  [ 0  6 45 14 23]]

 [[61 65 26 55 34]
  [46 19 26  8 80]
  [ 9 55  9 39 27]
  [ 4 94 43 71 95]]

 [[50 95 67 74 46]
  [43 21 61 97 58]
  [16 79 56 64 47]
  [20 73 62 85 76]]]


In [ ]:
#Indexacion y Slicing
# Crear array de ejemplo
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Array original:")
print(arr_2d)

# Indexación básica
print("\nIndexación básica:")
print("Elemento en (0,0):", arr_2d[0, 0])
print("Elemento en (2,3):", arr_2d[2, 3])

Array original:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Indexación básica:
Elemento en (0,0): 1
Elemento en (2,3): 12


In [ ]:
# Slicing básico
print("\nSlicing básico:")
print("Primera fila:", arr_2d[0, :])
print("Primera columna:", arr_2d[:, 0])
print("Submatriz 2x2 (esquina superior izquierda):")
print(arr_2d[:2, :2])
print("Submatriz 2x2 (esquina inferior derecha):")
print(arr_2d[1:, 2:])


Slicing básico:
Primera fila: [1 2 3 4]
Primera columna: [1 5 9]
Submatriz 2x2 (esquina superior izquierda):
[[1 2]
 [5 6]]
Submatriz 2x2 (esquina inferior derecha):
[[ 7  8]
 [11 12]]


In [ ]:
#Si yo quisiera seleccionar pero no usando los métodos de slicing sino con un #bucle en print("Primera fila:", arr_2d[0, :])

In [ ]:
primera_fila=[]
for j in range(arr_2d.shape[1]):
    primera_fila.append(arr_2d[0,j])
print("Primera fila:", primera_fila)

Primera fila: [np.int64(1), np.int64(2), np.int64(3), np.int64(4)]


In [ ]:
# Slicing con saltos
print("\nSlicing con saltos:")
print("Filas alternas:", arr_2d[::2, :])
print("Columnas alternas:", arr_2d[:, ::2])


Slicing con saltos:
Filas alternas: [[ 1  2  3  4]
 [ 9 10 11 12]]
Columnas alternas: [[ 1  3]
 [ 5  7]
 [ 9 11]]


In [ ]:
#array[inicio:fin:paso]

In [ ]:
# Indexación con arrays de booleanos
print("\nIndexación con condiciones booleanas:")
mask = arr_2d > 6
print("Máscara de elementos > 6:")
print(mask)
print("Elementos > 6:", arr_2d[mask])


Indexación con condiciones booleanas:
Máscara de elementos > 6:
[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
Elementos > 6: [ 7  8  9 10 11 12]


In [ ]:
#arr_2d <5
#arr_2d % 2==0 numeros pares
#(arr_2d >5) & (arr_2d < 10)

In [ ]:
#Operaciones Vectorizadas y Broadcasting
# Vectorización vs. bucles tradicionales
def suma_con_bucle(lista1, lista2):
    """Suma dos listas utilizando bucles."""
    resultado = []
    for i in range(len(lista1)):
        resultado.append(lista1[i] + lista2[i])
    return resultado

# Crear datos de prueba
tamano = 1000000
lista1 = list(range(tamano))
lista2 = list(range(tamano))
arr1 = np.array(lista1)
arr2 = np.array(lista2)

# Medir tiempo con bucles
inicio = time.time()
resultado_bucle = suma_con_bucle(lista1, lista2)
fin = time.time()
tiempo_bucle = fin - inicio
print(f"Tiempo con bucles (1000000 elementos): {tiempo_bucle:.6f} segundos")

# Medir tiempo con NumPy
inicio = time.time()
resultado_numpy = arr1 + arr2  # Todos los elementos
fin = time.time()
tiempo_numpy = fin - inicio
print(f"Tiempo con NumPy ({tamano} elementos): {tiempo_numpy:.6f} segundos")

Tiempo con bucles (1000000 elementos): 0.077610 segundos
Tiempo con NumPy (1000000 elementos): 0.004077 segundos


In [ ]:
# Operaciones aritméticas básicas
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("\nOperaciones aritméticas básicas:")
print("a + b =", a + b)
print("a - b =", a - b)
print("a * b =", a * b)  # Multiplicación elemento a elemento
print("a / b =", a / b)
print("a ** 2 =", a ** 2)  # Exponenciación
print("a % 2 =", a % 2)  # Módulo


Operaciones aritméticas básicas:
a + b = [5 7 9]
a - b = [-3 -3 -3]
a * b = [ 4 10 18]
a / b = [0.25 0.4  0.5 ]
a ** 2 = [1 4 9]
a % 2 = [1 0 1]


In [ ]:
# Funciones universales (ufuncs)
print("\nFunciones universales:")
print("Seno:", np.sin(a))
print("Exponencial:", np.exp(a))
print("Logaritmo natural:", np.log(a))
print("Suma de todos los elementos:", np.sum(a))
print("Valor mínimo:", np.min(a))
print("Valor máximo:", np.max(a))
print("Media aritmética:", np.mean(a))


Funciones universales:
Seno: [0.84147098 0.90929743 0.14112001]
Exponencial: [ 2.71828183  7.3890561  20.08553692]
Logaritmo natural: [0.         0.69314718 1.09861229]
Suma de todos los elementos: 6
Valor mínimo: 1
Valor máximo: 3
Media aritmética: 2.0


In [ ]:
#Broadcasting
# Ejemplo 1: Sumar un escalar a cada elemento
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array original:")
print(arr)
print("\nSumando 10 a cada elemento:")
print(arr + 10)

Array original:
[[1 2 3]
 [4 5 6]]

Sumando 10 a cada elemento:
[[11 12 13]
 [14 15 16]]


In [ ]:
# Ejemplo 2: Sumar un vector a cada fila
vector_fila = np.array([10, 20, 30])
print("\nSumando un vector a cada fila:")
print(arr + vector_fila)  # El vector se replica para cada fila


Sumando un vector a cada fila:
[[11 22 33]
 [14 25 36]]


In [ ]:
#Analisis estadístico con Pandas y Numpy
# Crear un DataFrame de ejemplo con datos sintéticos
np.random.seed(42)
n = 1000
df = pd.DataFrame({
    'edad': np.random.normal(35, 10, n).astype(int),
    'salario': np.random.normal(50000, 15000, n),
    'experiencia': np.random.normal(10, 5, n),
    'satisfaccion': np.random.uniform(1, 10, n),
    'departamento': np.random.choice(['Ventas', 'Marketing', 'IT', 'RRHH'], n)
})

In [ ]:
# Visualización de datos
print("Primeras filas del DataFrame:")
print(df.head())

Primeras filas del DataFrame:
   edad       salario  experiencia  satisfaccion departamento
0    39  70990.331549     6.624109      8.368662           IT
1    33  63869.505244     9.277407      9.852105    Marketing
2    41  50894.455549     6.037900      3.337038       Ventas
3    50  40295.948334     8.460192      9.727513       Ventas
4    32  60473.349704     0.531927      4.881105         RRHH


In [ ]:
#Salario redondeado a dos decimales, la experiencia a tres decimales, y la satisfaccion a un decimal
df['salario']=df['salario'].round(2)
df['experiencia']=df['experiencia'].round(3)
df['satisfaccion']=df['satisfaccion'].round(1)

In [ ]:
print(df.head())

   edad   salario  experiencia  satisfaccion departamento
0    39  70990.33        6.624           8.4           IT
1    33  63869.51        9.277           9.9    Marketing
2    41  50894.46        6.038           3.3       Ventas
3    50  40295.95        8.460           9.7       Ventas
4    32  60473.35        0.532           4.9         RRHH


In [ ]:
# Estadísticas descriptivas básicas
print("\nEstadísticas descriptivas:")
print(df.describe())


Estadísticas descriptivas:
              edad       salario  experiencia  satisfaccion
count  1000.000000   1000.000000  1000.000000   1000.000000
mean     34.674000  51062.543590    10.029169      5.414100
std       9.797741  14961.815629     4.917272      2.575687
min       2.000000   5894.170000    -5.098000      1.000000
25%      28.000000  40906.377500     6.759750      3.200000
50%      35.000000  50946.160000     9.998500      5.350000
75%      41.000000  60933.230000    13.304500      7.600000
max      73.000000  97896.610000    29.631000     10.000000


In [ ]:
# Estadísticas por grupo
print("\nEstadísticas por departamento:")
print(df.groupby('departamento')['salario'].describe())


Estadísticas por departamento:
              count          mean           std      min         25%  \
departamento                                                           
IT            222.0  51959.537973  15060.594542  6179.74  42744.8025   
Marketing     270.0  51851.253222  15413.521591  6916.07  40854.2750   
RRHH          254.0  50054.517756  14812.236924  9451.52  39857.1150   
Ventas        254.0  50448.190079  14526.391820  5894.17  41378.5175   

                    50%         75%       max  
departamento                                   
IT            51791.355  62868.6575  84789.94  
Marketing     51309.130  61258.0675  97896.61  
RRHH          49603.045  59809.9350  97066.23  
Ventas        50813.680  58903.6175  89025.25  


In [ ]:
# Medidas de tendencia central
print("\nMedidas de tendencia central para 'salario':")
print("Media:", df['salario'].mean())
print("Mediana:", df['salario'].median())
print("Moda:", df['salario'].mode()[0])


Medidas de tendencia central para 'salario':
Media: 51062.543589999994
Mediana: 50946.16
Moda: 5894.17


In [ ]:
#otras medidas de tendencia central
from scipy.stats import trim_mean
trim_mean(df['salario'], 0.1)  # recorta 10% de cada extremo


np.float64(51112.863)

In [ ]:
from scipy.stats import gmean
gmean(df['salario'])


np.float64(48446.22739389989)

In [ ]:
from scipy.stats import hmean
hmean(df['salario'][df['salario'] > 0])  # evita valores <= 0


np.float64(44767.12326298403)

In [ ]:
df['salario'].quantile(0.25)  # cuartil 1
df['salario'].quantile(0.75)  # cuartil 3


np.float64(60933.23)

In [ ]:
#Medidas de variabilidad
# Medidas de dispersión
print("\nMedidas de dispersión para 'salario':")
print("Rango:", df['salario'].max() - df['salario'].min())
print("Varianza:", df['salario'].var())
print("Desviación estándar:", df['salario'].std())
print("Coeficiente de variación:", df['salario'].std() / df['salario'].mean())


Medidas de dispersión para 'salario':
Rango: 92002.44
Varianza: 223855926.92475948
Desviación estándar: 14961.815629286422
Coeficiente de variación: 0.2930096030746208


In [ ]:
#Otras medidas de variabilidad
iqr = df['salario'].quantile(0.75) - df['salario'].quantile(0.25)
print(iqr)


20026.8525


In [ ]:
#Desviación absoluta media (MAD)
mad = df['salario'].mad()
print(mad)
#Seguramente porque no existe más en la nueva version de pandas

AttributeError: 'Series' object has no attribute 'mad'

In [ ]:
mad = (df['salario'] - df['salario'].mean()).abs().mean()
print("Desviación absoluta media (MAD):", mad)


Desviación absoluta media (MAD): 11852.56305872


In [ ]:
#medidas de forma
from scipy.stats import skew
asimetria = skew(df['salario'])


In [ ]:
print(asimetria)

-0.04932176568385262


In [ ]:
from scipy.stats import kurtosis
curtosis = kurtosis(df['salario'])
print(curtosis)


0.052117522609953504


In [ ]:
curtosis_estandar = kurtosis(df['salario'], fisher=False)
print(curtosis_estandar)

3.0521175226099535


In [ ]:
pearson_skew = 3 * (df['salario'].mean() - df['salario'].median()) / df['salario'].std()


In [ ]:
from scipy.stats import moment
moment_3 = moment(df['salario'], moment=3)  # Asimetría
moment_4 = moment(df['salario'], moment=4)  # Curtosis


In [ ]:
corr_matrix = df.select_dtypes(include=[np.number]).corr()
print("Matriz de correlación:")
print(corr_matrix)


Matriz de correlación:
                  edad   salario  experiencia  satisfaccion
edad          1.000000 -0.041490     0.021923      0.019024
salario      -0.041490  1.000000    -0.011202      0.034373
experiencia   0.021923 -0.011202     1.000000      0.015176
satisfaccion  0.019024  0.034373     0.015176      1.000000


In [ ]:
print("Coeficiente de Pearson:", df['salario'].corr(df['experiencia']))

Coeficiente de Pearson: -0.011201770588713557


In [ ]:
print("Coeficiente de Spearman (rangos):",
      df['salario'].corr(df['experiencia'], method='spearman'))

Coeficiente de Spearman (rangos): -0.00919303596525102
